version: '3'
services:
  app:
    build: .
    ports:
      - "${PORT}:3000"
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_PORT: ${DB_PORT}
    ports:
      - "5432:5432"
